spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/meme
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

meme:
  cloud:
    google:
      project-id: "utility-ratio-448006-a2"
      bucket-name: "memetagger"
      credentials: file:/etc/certs/googleCloud.json

  rsa:
    private-key: file:/etc/certs/private.pem
    public-key: file:/etc/certs/public.pem
